# Generated by Django 5.2.6 on 2026-09-23 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='PO', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('ref_quote_number', models.CharField(blank=True, default='', max_length=100)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('prepared_by', models.CharField(blank=True, default='', max_length=255)),
                ('vendor', models.JSONField(blank=True, default=dict)),
                ('intro_text', models.TextField(blank=True, default='')),
                ('items', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('include_amount_details', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('delivery', models.JSONField(blank=True, default=dict)),
                ('payment', models.JSONField(blank=True, default=dict)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('signatures', models.JSONField(blank=True, default=dict)),
                ('document_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='previewed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
