# Generated by Django 5.2.6 on 2026-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='PO/PDF/'),
        ),
    ]
