# Generated by Django 5.2.6 on 2026-09-24 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_purchaseorder_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='QTN', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('quotation', 'Quotation'), ('other', 'Other')], default='purchase_order', max_length=30),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('quotation_date', models.DateField()),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('intro', models.TextField(blank=True, default='')),
                ('items', models.JSONField(default=list)),
                ('technical_details', models.JSONField(default=list)),
                ('terms', models.JSONField(default=list)),
                ('signatures', models.JSONField(default=dict)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='erp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
