# Generated by Django 5.2.6 on 2026-09-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_quotationnumbersettings_alter_customer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotations/'),
        ),
    ]
