# Generated by Django 5.2.6 on 2026-09-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_quotation_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='DC', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('quotation', 'Quotation'), ('delivery_challan', 'Delivery Challan'), ('other', 'Other')], default='purchase_order', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(max_length=50, unique=True)),
                ('dc_date', models.DateField()),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, default='', max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('delivery_at', models.CharField(blank=True, default='', max_length=255)),
                ('company_address_id', models.CharField(blank=True, default='unit1', max_length=50)),
                ('returnable', models.BooleanField(default=False)),
                ('items', models.JSONField(default=list)),
                ('amount_in_words', models.TextField(blank=True, default='')),
                ('prepared_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='delivery_challans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='erp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
