# Generated by Django 5.2.6 on 2026-09-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_taxinvoice_taxinvoicenumbersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
