# Generated by Django 5.2.6 on 2026-09-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_customer_state_customer_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('customer_po_no', models.CharField(blank=True, default='', max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=150)),
                ('receiver_details', models.JSONField(blank=True, default=dict)),
                ('receiver_gst', models.CharField(blank=True, default='', max_length=50)),
                ('receiver_address_option_id', models.CharField(blank=True, default='', max_length=50)),
                ('consignee_details', models.JSONField(blank=True, default=dict)),
                ('consignee_gst', models.CharField(blank=True, default='', max_length=50)),
                ('consignee_address_option_id', models.CharField(blank=True, default='', max_length=50)),
                ('company_address_id', models.CharField(blank=True, default='unit1', max_length=50)),
                ('items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rounded_off', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_in_words', models.TextField(blank=True, default='')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('declaration', models.TextField(blank=True, default='')),
                ('enclosure_text', models.TextField(blank=True, default='')),
                ('document_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='proforma_invoices/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='PF', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('quotation', 'Quotation'), ('delivery_challan', 'Delivery Challan'), ('tax_invoice', 'Tax Invoice'), ('proforma_invoice', 'Proforma Invoice'), ('other', 'Other')], default='purchase_order', max_length=30),
        ),
    ]
