# Generated by Django 5.2.6 on 2026-09-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_proformainvoice_proformainvoicenumbersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='delivery_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
    ]
