# Generated by Django 5.2.6 on 2026-09-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_deliverychallan_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=20)),
                ('category', models.CharField(choices=[('Purchase', 'Purchase'), ('Transport', 'Transport'), ('Salary', 'Salary'), ('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Maintenance', 'Maintenance'), ('Office', 'Office'), ('Sales', 'Sales'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=30)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
