# Generated by Django 5.2.6 on 2026-09-28 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Manually entered employee ID, e.g. EMP001 or TRX-001.', max_length=50, unique=True)),
                ('employee_code', models.CharField(blank=True, default='', help_text='Optional secondary code (e.g. payroll code).', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.URLField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='', max_length=20)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Production', 'Production'), ('HR', 'HR'), ('Sales', 'Sales'), ('Accounts', 'Accounts')], default='', max_length=50)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=150)),
                ('employment_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Probation', 'Probation'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Intern', 'Intern'), ('Consultant', 'Consultant')], default='', max_length=20)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('On Notice', 'On Notice')], default='Active', max_length=20)),
                ('reporting_manager', models.CharField(blank=True, default='', max_length=150)),
                ('work_location', models.CharField(blank=True, default='', max_length=150)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('aadhaar', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('uan', models.CharField(blank=True, default='', max_length=20)),
                ('pf', models.CharField(blank=True, default='', max_length=20)),
                ('esi', models.CharField(blank=True, default='', max_length=20)),
                ('passport', models.CharField(blank=True, default='', max_length=20)),
                ('driving_license', models.CharField(blank=True, default='', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('employment_history', models.JSONField(blank=True, default=list)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['archived'], name='erp_employe_archive_d2c090_idx'), models.Index(fields=['employee_id'], name='erp_employe_employe_784d23_idx'), models.Index(fields=['department'], name='erp_employe_departm_f55466_idx'), models.Index(fields=['city'], name='erp_employe_city_df4b6c_idx'), models.Index(fields=['employment_status'], name='erp_employe_employm_953170_idx')],
            },
        ),
    ]
