# Generated by Django 5.2.6 on 2026-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='EMP', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
