# Generated by Django 5.2.6 on 2026-09-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
