# Generated by Django 5.2.6 on 2026-09-28 04:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PARTIALLY_REPAID', 'Partially Repaid'), ('FULLY_REPAID', 'Fully Repaid')], default='OUTSTANDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='erp.employee')),
            ],
            options={
                'ordering': ['-advance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly Off'), ('WFH', 'Work From Home')], default='PRESENT', max_length=20)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='erp.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=7)),
                ('salary_year', models.PositiveIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('attendance_wage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('esi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='erp.employee')),
            ],
            options={
                'ordering': ['-salary_month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='erp.advance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_repayments', to='erp.employee')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_repayments', to='erp.salarypayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly')], default='HOURLY', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('paid_leave_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=10)),
                ('holiday_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=10)),
                ('weekly_off_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wage_config', to='erp.employee')),
            ],
            options={
                'verbose_name': 'Wage Config',
                'verbose_name_plural': 'Wage Configs',
            },
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['employee'], name='erp_advance_employe_6b52df_idx'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['advance_date'], name='erp_advance_advance_2f5cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['status'], name='erp_advance_status_0f81df_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='erp_attenda_date_5d1210_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='erp_attenda_employe_699006_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='erp_attenda_status_78dbbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_employee_date'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['employee', 'salary_month'], name='erp_salaryp_employe_26185b_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['salary_year'], name='erp_salaryp_salary__5d6a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['payment_status'], name='erp_salaryp_payment_5fa9a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(fields=('employee', 'salary_month'), name='unique_salary_payment_employee_month'),
        ),
        migrations.AddIndex(
            model_name='advancerepayment',
            index=models.Index(fields=['employee'], name='erp_advance_employe_1f225c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerepayment',
            index=models.Index(fields=['advance'], name='erp_advance_advance_d75d19_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerepayment',
            index=models.Index(fields=['salary_payment'], name='erp_advance_salary__7a31ec_idx'),
        ),
    ]
