# Generated by Django 5.2.6 on 2026-09-28 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_advance_attendance_salarypayment_advancerepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=7)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('esi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_adjustments', to='erp.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'salary_month'], name='erp_salarya_employe_360659_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'salary_month'), name='unique_salary_adjustment_employee_month')],
            },
        ),
    ]
