# Generated by Django 5.2.6 on 2026-09-29 04:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_advance_salarypayment_advancerepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('HOURLY', 'Hourly Wage'), ('MONTHLY', 'Monthly Salary')], default='HOURLY', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_leave_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=20)),
                ('holiday_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=20)),
                ('weekly_off_policy', models.CharField(choices=[('UNPAID', 'Unpaid'), ('FULL_DAY', 'Paid Full Day')], default='UNPAID', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wage_configuration', to='erp.employee')),
            ],
            options={
                'db_table': 'wage_configuration',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('PAID_LEAVE', 'Paid Leave'), ('UNPAID_LEAVE', 'Unpaid Leave'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly Off'), ('WFH', 'Work From Home')], max_length=20)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='erp.employee')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-date', 'employee__employee_id'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_9ec8ab_idx'), models.Index(fields=['date'], name='attendance__date_21321a_idx'), models.Index(fields=['status'], name='attendance__status_40d6e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_date')],
            },
        ),
    ]
