# Generated by Django 5.2.6 on 2026-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
