# Generated by Django 5.2.6 on 2026-10-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_purchaseorderitem_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=100, unique=True)),
                ('grn_type', models.CharField(choices=[('PO', 'Purchase Order'), ('DIRECT', 'Direct')], default='PO', max_length=20)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('po_description', models.TextField(blank=True, default='')),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('consumable_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('pending_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('warehouse', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Received', 'Partially Received'), ('Fully Received', 'Fully Received')], default='Pending', max_length=30)),
                ('received_by', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='erp.purchaseorderitem')),
            ],
        ),
    ]
