# Generated by Django 5.2.6 on 2026-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_consumablegrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablegrn',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('Unit One', 'Unit One'), ('Unit Two', 'Unit Two')], default='', max_length=50),
        ),
    ]
