# Generated by Django 5.2.6 on 2026-10-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_alter_consumablegrn_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=100, unique=True)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('po_description', models.TextField(blank=True, default='')),
                ('consumable_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('quantity_issued', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_card', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='erp.consumablegrn')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grn'], name='erp_consuma_grn_id_b4b69f_idx'), models.Index(fields=['po_number'], name='erp_consuma_po_numb_5dbfb4_idx')],
            },
        ),
    ]
