# Generated by Django 5.2.6 on 2026-10-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_consumableissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=100, unique=True)),
                ('issue_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('consumable_name', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse', models.CharField(blank=True, default='', max_length=50)),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('returned_by', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Partially Returned', 'Partially Returned'), ('Fully Returned', 'Fully Returned')], db_index=True, default='Issued', max_length=30),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['status'], name='erp_consuma_status_bace5c_idx'),
        ),
        migrations.AddField(
            model_name='consumablereturn',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.consumableissue'),
        ),
        migrations.AddIndex(
            model_name='consumablereturn',
            index=models.Index(fields=['issue'], name='erp_consuma_issue_i_c93cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='consumablereturn',
            index=models.Index(fields=['issue_number'], name='erp_consuma_issue_n_39449d_idx'),
        ),
    ]
