# Generated by Django 5.2.6 on 2026-10-04 03:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_consumablereturn_consumableissue_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwg_number', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('revision', models.CharField(default='REV-00', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_number', models.CharField(blank=True, default='', max_length=50)),
                ('item_number', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('std', models.CharField(blank=True, default='-', max_length=100)),
                ('drawing_number', models.CharField(blank=True, default='-', max_length=100)),
                ('item_no', models.CharField(blank=True, default='', max_length=50)),
                ('var_no', models.CharField(blank=True, default='-', max_length=50)),
                ('material_code', models.CharField(db_index=True, max_length=100)),
                ('material_specn', models.CharField(blank=True, default='', max_length=200)),
                ('acp', models.CharField(blank=True, default='-', max_length=50)),
                ('di', models.CharField(blank=True, default='-', max_length=50)),
                ('unit', models.CharField(default='Nos', max_length=30)),
                ('unit_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Informational only. Not used for stock consumption.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Controlling quantity for material requirements.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='erp.drawing')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Active', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='erp.project'),
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('project', 'dwg_number', 'revision'), name='unique_project_drawing_revision'),
        ),
    ]
