# Generated by Django 5.2.6 on 2026-10-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_drawing_bomitem_project_drawing_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Structured description e.g. {"material_type": "Plate", "thickness": 6, "length": 530, "width": 530}'),
        ),
    ]
