# Generated by Django 5.2.6 on 2026-10-04 04:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_bomitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMPOIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('is_dummy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_integrations', to='erp.bomitem')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_integrations', to='erp.purchaseorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bom_item'], name='erp_bompoin_bom_ite_d3a03a_idx'), models.Index(fields=['purchase_order_item'], name='erp_bompoin_purchas_cabc3d_idx')],
            },
        ),
    ]
