# Generated by Django 5.2.6 on 2026-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_bompointegration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bompointegration',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bompointegration',
            name='erp_bompoin_bom_ite_d3a03a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bompointegration',
            name='erp_bompoin_purchas_cabc3d_idx',
        ),
    ]
