# Generated by Django 5.2.6 on 2026-10-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_alter_bompointegration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bompointegration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bompointegration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_integrations', to='erp.project'),
        ),
        migrations.AlterField(
            model_name='bompointegration',
            name='bom_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_integrations', to='erp.bomitem'),
        ),
        migrations.AddIndex(
            model_name='bompointegration',
            index=models.Index(fields=['project'], name='erp_bompoin_project_882db6_idx'),
        ),
        migrations.AddIndex(
            model_name='bompointegration',
            index=models.Index(fields=['bom_item'], name='erp_bompoin_bom_ite_d3a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='bompointegration',
            index=models.Index(fields=['purchase_order_item'], name='erp_bompoin_purchas_cabc3d_idx'),
        ),
    ]
