# Generated by Django 5.2.6 on 2026-10-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_dummypurchaseorder_dummypurchaseorderitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bompointegration',
            name='erp_bompoin_project_882db6_idx',
        ),
        migrations.RemoveIndex(
            model_name='bompointegration',
            name='erp_bompoin_bom_ite_d3a03a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bompointegration',
            name='erp_bompoin_purchas_cabc3d_idx',
        ),
        migrations.AddField(
            model_name='bompointegration',
            name='dummy_purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='erp.dummypurchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='bompointegration',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_integrations', to='erp.purchaseorderitem'),
        ),
        migrations.AddConstraint(
            model_name='bompointegration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dummy_purchase_order_item__isnull', True), ('purchase_order_item__isnull', False)), models.Q(('dummy_purchase_order_item__isnull', False), ('purchase_order_item__isnull', True)), _connector='OR'), name='bompo_exactly_one_item'),
        ),
    ]
