# Generated by Django 5.2.6 on 2026-10-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_bompo_add_dummy_fk_and_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGRNNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='GRN', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('grn_date', models.DateField(auto_now_add=True)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('receiving_unit', models.CharField(blank=True, default='', max_length=50)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('received_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_grns_created', to=settings.AUTH_USER_MODEL)),
                ('dummy_purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_grns', to='erp.dummypurchaseorderitem')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_grns', to='erp.purchaseorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_order_item'], name='erp_materia_purchas_9982a5_idx'), models.Index(fields=['dummy_purchase_order_item'], name='erp_materia_dummy_p_468418_idx'), models.Index(fields=['grn_number'], name='erp_materia_grn_num_f731b7_idx'), models.Index(fields=['po_number'], name='erp_materia_po_numb_1222cb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dummy_purchase_order_item__isnull', True), ('purchase_order_item__isnull', False)), models.Q(('dummy_purchase_order_item__isnull', False), ('purchase_order_item__isnull', True)), _connector='OR'), name='materialgrn_exactly_one_item')],
            },
        ),
    ]
