# Generated by Django 5.2.6 on 2026-10-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_materialgrn_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='length',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='thickness',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='width',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
