# Generated by Django 5.2.6 on 2026-10-05 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_purchaseorderitem_length_purchaseorderitem_thickness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2')], default='Unit 1', max_length=50)),
                ('source_type', models.CharField(choices=[('PO', 'PO'), ('Dummy PO', 'Dummy PO'), ('Job Remaining', 'Job Remaining'), ('Cutting Remaining', 'Cutting Remaining'), ('Rework', 'Rework'), ('Other', 'Other')], default='PO', max_length=30)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_spec', models.CharField(blank=True, default='', max_length=200)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('heat_number', models.CharField(blank=True, default='', max_length=100)),
                ('plate_number', models.CharField(blank=True, default='', max_length=100)),
                ('original_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('stock_status', models.CharField(choices=[('Available', 'Available'), ('Partially Used', 'Partially Used'), ('Remaining', 'Remaining'), ('Cutting Remaining', 'Cutting Remaining')], default='Available', max_length=30)),
                ('rework_required', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_created', to=settings.AUTH_USER_MODEL)),
                ('dummy_purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='erp.dummypurchaseorderitem')),
                ('material_grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='erp.materialgrn')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='erp.project')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='erp.purchaseorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=5)),
                ('movement_type', models.CharField(choices=[('GRN', 'Goods Receipt'), ('Issue Job Work', 'Issue to Job Work'), ('Return Job Work', 'Return from Job Work'), ('Issue Production', 'Issue to Production'), ('Cutting', 'Cutting'), ('Rework', 'Rework'), ('Scrap', 'Scrap'), ('Adjustment', 'Manual Adjustment')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.materialstock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='materialstock',
            index=models.Index(fields=['stock_id'], name='erp_materia_stock_i_6f737e_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstock',
            index=models.Index(fields=['unit'], name='erp_materia_unit_bb6826_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstock',
            index=models.Index(fields=['source_type'], name='erp_materia_source__1fcf36_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstock',
            index=models.Index(fields=['po_number'], name='erp_materia_po_numb_9dc83d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstock',
            index=models.Index(fields=['stock_status'], name='erp_materia_stock_s_2af98d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstockmovement',
            index=models.Index(fields=['stock'], name='erp_materia_stock_i_0485fc_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstockmovement',
            index=models.Index(fields=['direction'], name='erp_materia_directi_33ee9f_idx'),
        ),
        migrations.AddIndex(
            model_name='materialstockmovement',
            index=models.Index(fields=['movement_type'], name='erp_materia_movemen_8ecdef_idx'),
        ),
    ]
