# Generated by Django 5.2.6 on 2026-10-05 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_materialstock_materialstockmovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkIssueNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='ISS', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobWorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('process_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_spec', models.CharField(blank=True, default='', max_length=200)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('job_work_type', models.CharField(choices=[('In-House', 'In-House'), ('Outsourcing', 'Outsourcing')], default='In-House', max_length=20)),
                ('process_name', models.CharField(blank=True, default='', max_length=150)),
                ('process_id', models.CharField(blank=True, default='', max_length=50)),
                ('job_work_unit', models.CharField(blank=True, default='', max_length=50)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, default='', max_length=100)),
                ('job_work_location', models.CharField(blank=True, default='', max_length=255)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('quantity_issued', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Partially Returned', 'Partially Returned'), ('Fully Returned', 'Fully Returned'), ('Cancelled', 'Cancelled')], default='Issued', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_issues_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_issues', to='erp.project')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_issues', to='erp.materialstock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_number'], name='erp_jobwork_issue_n_4b3911_idx'), models.Index(fields=['stock'], name='erp_jobwork_stock_i_f1c289_idx'), models.Index(fields=['po_number'], name='erp_jobwork_po_numb_0633d1_idx'), models.Index(fields=['job_work_type'], name='erp_jobwork_job_wor_9437b0_idx'), models.Index(fields=['status'], name='erp_jobwork_status_0a072d_idx')],
            },
        ),
    ]
