# Generated by Django 5.2.6 on 2026-10-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_jobwork_process_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkReceiveNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='JWR', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobWorkReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('job_work_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_spec', models.CharField(blank=True, default='', max_length=200)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('process_name', models.CharField(blank=True, default='', max_length=150)),
                ('process_id', models.CharField(blank=True, default='', max_length=50)),
                ('completed_input_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remaining_input_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_output_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_output_weight', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('total_remaining_weight', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('received_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_receives_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receives', to='erp.jobworkissue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_receives', to='erp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkReceivePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_no', models.CharField(blank=True, default='', max_length=100)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_pieces', to='erp.jobworkreceive')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkReceiveRemaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(blank=True, default='', max_length=100)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('rework_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remaining_pieces', to='erp.jobworkreceive')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='jobworkreceive',
            index=models.Index(fields=['receive_number'], name='erp_jobwork_receive_4b7efd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkreceive',
            index=models.Index(fields=['issue'], name='erp_jobwork_issue_i_7bc382_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkreceive',
            index=models.Index(fields=['job_work_id'], name='erp_jobwork_job_wor_604cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkreceive',
            index=models.Index(fields=['po_number'], name='erp_jobwork_po_numb_134a12_idx'),
        ),
    ]
