# Generated by Django 5.2.6 on 2026-10-06 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_jobworkreceivenumbersettings_jobworkreceive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionIssueNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='IP', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('job_work_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('po_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('po_type', models.CharField(blank=True, default='', max_length=50)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_spec', models.CharField(blank=True, default='', max_length=200)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('job_work_type', models.CharField(blank=True, default='', max_length=30)),
                ('job_work_unit', models.CharField(blank=True, default='', max_length=50)),
                ('process_name', models.CharField(blank=True, default='', max_length=150)),
                ('process_id', models.CharField(blank=True, default='', max_length=50)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('piece_no', models.CharField(blank=True, default='', max_length=100)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('original_received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('previously_issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remaining_available_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('issued_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('In Production', 'In Production'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Issued', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_issues_created', to=settings.AUTH_USER_MODEL)),
                ('job_work_piece', models.ForeignKey(blank=True, help_text='The specific piece this issue was drawn from. Nullable for legacy rows created before piece-level tracking was added.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_issues', to='erp.jobworkreceivepiece')),
                ('job_work_receive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_issues', to='erp.jobworkreceive')),
                ('material_stock', models.ForeignKey(blank=True, help_text='The stock lot the piece corresponds to. Set at create time if a lot was created for this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_issues', to='erp.materialstock')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_issues', to='erp.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue_number'], name='erp_product_issue_n_55b30f_idx'), models.Index(fields=['job_work_receive'], name='erp_product_job_wor_c77b2a_idx'), models.Index(fields=['job_work_piece'], name='erp_product_job_wor_15ed06_idx'), models.Index(fields=['job_work_id'], name='erp_product_job_wor_794c8c_idx'), models.Index(fields=['po_number'], name='erp_product_po_numb_3ea994_idx'), models.Index(fields=['status'], name='erp_product_status_b2029d_idx')],
            },
        ),
    ]
