# Generated by Django 5.2.6 on 2026-10-07 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_productionissuenumbersettings_productionissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='ASM', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=30)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assemblies', to='erp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('material', 'Material'), ('assembly', 'Assembly')], max_length=20)),
                ('use_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('material_name', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=30)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('drawing_number', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='erp.assembly')),
                ('job_work_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_inputs', to='erp.jobworkreceivepiece')),
                ('source_assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_by_inputs', to='erp.assembly')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('process_id', models.CharField(max_length=50)),
                ('qc_required', models.BooleanField(default=False)),
                ('execution_type', models.CharField(choices=[('In-House', 'In-House'), ('Outsourcing', 'Outsourcing')], default='In-House', max_length=20)),
                ('execution_unit', models.CharField(blank=True, default='', max_length=50)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_location', models.CharField(blank=True, default='', max_length=255)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('outsourcing_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='erp.assembly')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['assembly_id'], name='erp_assembl_assembl_8847ba_idx'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['project'], name='erp_assembl_project_7d20f2_idx'),
        ),
        migrations.AddIndex(
            model_name='assembly',
            index=models.Index(fields=['status'], name='erp_assembl_status_ec536d_idx'),
        ),
        migrations.AddConstraint(
            model_name='assemblyinput',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job_work_piece__isnull', False), ('source_assembly__isnull', True), ('source_type', 'material')), models.Q(('job_work_piece__isnull', True), ('source_assembly__isnull', False), ('source_type', 'assembly')), _connector='OR'), name='assembly_input_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='assemblyprocess',
            constraint=models.UniqueConstraint(fields=('assembly', 'sequence'), name='assembly_process_unique_sequence'),
        ),
    ]
