# Generated by Django 5.2.6 on 2026-10-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_assemblynumbersettings_assembly_assemblyinput_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assemblynumbersettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='assemblynumbersettings_single_active'),
        ),
    ]
