# Generated by Django 5.2.6 on 2026-10-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_assemblynumbersettings_assemblynumbersettings_single_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReworkNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='RWK', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='erp.assembly')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='erp.assemblyexecution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyStageExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('process_id', models.CharField(max_length=50)),
                ('qc_required', models.BooleanField(default=False)),
                ('execution_type', models.CharField(choices=[('In-House', 'In-House'), ('Outsourcing', 'Outsourcing')], default='In-House', max_length=20)),
                ('execution_unit', models.CharField(blank=True, default='', max_length=50)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_contact', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_location', models.CharField(blank=True, default='', max_length=255)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('available_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('pending_operation_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('sent_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('awaiting_qc_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('rework_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('released_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_rows', to='erp.assemblyprocess')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='erp.assemblyexecution')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyStageMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('Start', 'Start'), ('Complete', 'Complete'), ('QC Accept', 'QC Accept'), ('QC Reject', 'QC Reject'), ('Rework Done', 'Rework Done'), ('Send Out', 'Send Out'), ('Receive In', 'Receive In'), ('Release', 'Release')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('performed_by', models.CharField(blank=True, default='', max_length=150)),
                ('supervised_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('dc_ref', models.CharField(blank=True, default='', max_length=50)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_stage_movements_created', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.assemblystageexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rework_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('job-work-receive', 'Receive From Job Work'), ('production', 'Production Operation')], db_index=True, default='production', max_length=30)),
                ('project_code', models.CharField(blank=True, default='', max_length=100)),
                ('po_number', models.CharField(blank=True, default='', max_length=100)),
                ('po_description', models.TextField(blank=True, default='')),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('material', models.CharField(blank=True, default='', max_length=150)),
                ('material_code', models.CharField(blank=True, default='', max_length=100)),
                ('material_spec', models.CharField(blank=True, default='', max_length=200)),
                ('thickness', models.CharField(blank=True, default='', max_length=50)),
                ('length', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=50)),
                ('job_work_piece_no', models.CharField(blank=True, default='', max_length=100)),
                ('assembly_code', models.CharField(blank=True, default='', max_length=50)),
                ('process_name', models.CharField(blank=True, default='', max_length=150)),
                ('process_id', models.CharField(blank=True, default='', max_length=50)),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('completed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('reason', models.TextField(blank=True, default='', help_text='Why this was flagged for rework.')),
                ('flagged_by', models.CharField(blank=True, default='', max_length=150)),
                ('rework_by', models.CharField(blank=True, default='', max_length=150)),
                ('supervisor', models.CharField(blank=True, default='', max_length=150)),
                ('start_remarks', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('qc_required', models.BooleanField(default=False)),
                ('qc_verified_by', models.CharField(blank=True, default='', max_length=150)),
                ('qc_result', models.CharField(blank=True, default='', max_length=20)),
                ('qc_remarks', models.TextField(blank=True, default='')),
                ('qc_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Rework Required', 'Rework Required'), ('Rework In Progress', 'Rework In Progress'), ('Partially Completed', 'Partially Completed'), ('QC Pending', 'QC Pending'), ('Ready for Next Process', 'Ready for Next Process'), ('Available in Material Stock', 'Available in Material Stock'), ('Cancelled', 'Cancelled')], db_index=True, default='Rework Required', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to='erp.assemblystageexecution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records_created', to=settings.AUTH_USER_MODEL)),
                ('job_work_remaining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to='erp.jobworkreceiveremaining')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to='erp.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_text', models.TextField()),
                ('performed_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='erp.reworkrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReworkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('completed_by', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_completions_created', to=settings.AUTH_USER_MODEL)),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='erp.reworkrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assemblyexecution',
            index=models.Index(fields=['status'], name='erp_assembl_status_5be3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyexecutionevent',
            index=models.Index(fields=['execution'], name='erp_assembl_executi_e5a0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblystageexecution',
            index=models.Index(fields=['execution'], name='erp_assembl_executi_109676_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblystageexecution',
            index=models.Index(fields=['sequence'], name='erp_assembl_sequenc_ec0c34_idx'),
        ),
        migrations.AddConstraint(
            model_name='assemblystageexecution',
            constraint=models.UniqueConstraint(fields=('execution', 'sequence'), name='assemblystageexec_unique_sequence'),
        ),
        migrations.AddIndex(
            model_name='assemblystagemovement',
            index=models.Index(fields=['stage'], name='erp_assembl_stage_i_f81777_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblystagemovement',
            index=models.Index(fields=['movement'], name='erp_assembl_movemen_f7bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkrecord',
            index=models.Index(fields=['rework_number'], name='erp_reworkr_rework__239675_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkrecord',
            index=models.Index(fields=['source_type'], name='erp_reworkr_source__b299bb_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkrecord',
            index=models.Index(fields=['status'], name='erp_reworkr_status_103c01_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkrecord',
            index=models.Index(fields=['project'], name='erp_reworkr_project_9dda54_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkhistory',
            index=models.Index(fields=['rework'], name='erp_reworkh_rework__cc9edd_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkcompletion',
            index=models.Index(fields=['rework'], name='erp_reworkc_rework__a2367c_idx'),
        ),
    ]
