# Generated by Django 5.2.6 on 2026-10-07 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_reworknumbersettings_assemblyexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='DISP', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='dispatchnumbersettings_single_active')],
            },
        ),
        migrations.CreateModel(
            name='DispatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dc_challan_number', models.CharField(blank=True, db_index=True, default='', help_text='Delivery Challan number raised for this shipment.', max_length=100)),
                ('dispatch_date', models.DateField()),
                ('dispatch_time', models.CharField(blank=True, default='', max_length=10)),
                ('assembly_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('project_code', models.CharField(blank=True, default='', max_length=100)),
                ('dwg_description', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('dispatch_to', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('transporter', models.CharField(blank=True, default='', max_length=255)),
                ('driver_name', models.CharField(blank=True, default='', max_length=150)),
                ('driver_contact', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='erp.assemblyexecution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_challan', models.ForeignKey(blank=True, help_text='Optional link to the Delivery Challan record, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_transactions', to='erp.deliverychallan')),
            ],
            options={
                'ordering': ['-dispatch_date', '-created_at'],
                'indexes': [models.Index(fields=['assembly_execution'], name='erp_dispatc_assembl_519927_idx'), models.Index(fields=['assembly_code'], name='erp_dispatc_assembl_79bb2b_idx'), models.Index(fields=['dispatch_date'], name='erp_dispatc_dispatc_d0f85f_idx')],
            },
        ),
    ]
