# Generated by Django 5.2.6 on 2026-10-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_dispatchnumbersettings_dispatchtransaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispatchtransaction',
            index=models.Index(fields=['dc_challan_number'], name='erp_dispatc_dc_chal_92f9de_idx'),
        ),
    ]
