# Generated by Django 5.2.6 on 2026-10-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_dispatchtransaction_erp_dispatc_dc_chal_92f9de_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DispatchNumberSettings',
        ),
        migrations.DeleteModel(
            name='DispatchTransaction',
        ),
    ]
