# Generated by Django 5.2.6 on 2026-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_dispatchnumbersettings_dispatchtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_spec',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
