# Generated by Django 5.2.6 on 2026-10-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_purchaseorderitem_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('process', models.CharField(max_length=100)),
                ('scrap_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('Nos', 'Nos'), ('Kg', 'Kg'), ('Ton', 'Ton'), ('Meter', 'Meter'), ('Piece', 'Piece')], default='', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('Kg', 'Kg'), ('Ton', 'Ton')], default='', max_length=20)),
                ('reason', models.CharField(max_length=150)),
                ('scrap_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_records', to='erp.project')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_records', to='erp.purchaseorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scrap_id'], name='erp_scrap_scrap_i_987dcb_idx'), models.Index(fields=['purchase_order_item'], name='erp_scrap_purchas_ffa2e4_idx'), models.Index(fields=['project'], name='erp_scrap_project_150996_idx'), models.Index(fields=['scrap_date'], name='erp_scrap_scrap_d_5ac94d_idx'), models.Index(fields=['scrap_type'], name='erp_scrap_scrap_t_45b81a_idx')],
            },
        ),
    ]
