# Generated by Django 5.2.6 on 2026-10-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_scrapnumbersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('inform_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed')], default='PENDING', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
