# Generated by Django 5.2.6 on 2026-10-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='erp.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['purchase_order'], name='erp_journal_purchas_e97f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['po_number'], name='erp_journal_po_numb_021b65_idx'),
        ),
    ]
