# Generated by Django 5.2.6 on 2026-10-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_journalentry_po_number_journalentry_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
